// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvVDCe_C7PSncR36li36K6f6HKRuryJSo',
    appId: '1:394583557535:web:e2a1708aa9922ad48a69aa',
    messagingSenderId: '394583557535',
    projectId: 'ftk-firebase',
    authDomain: 'ftk-firebase.firebaseapp.com',
    storageBucket: 'ftk-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwYKyv6veUIJFXgvbK0w7Jk60mJ2svLXY',
    appId: '1:394583557535:android:977a79e2d482f7ea8a69aa',
    messagingSenderId: '394583557535',
    projectId: 'ftk-firebase',
    storageBucket: 'ftk-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD--nXjN1QldNoVql07g2UpmZ-3AdpvhGU',
    appId: '1:394583557535:ios:4eea53ee3b3609108a69aa',
    messagingSenderId: '394583557535',
    projectId: 'ftk-firebase',
    storageBucket: 'ftk-firebase.appspot.com',
    iosClientId: '394583557535-fjus28u1cb6bce01kgog79ikkmdenqmt.apps.googleusercontent.com',
    iosBundleId: 'gatosanonimos.ftkClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD--nXjN1QldNoVql07g2UpmZ-3AdpvhGU',
    appId: '1:394583557535:ios:f20ad19a00f2cb638a69aa',
    messagingSenderId: '394583557535',
    projectId: 'ftk-firebase',
    storageBucket: 'ftk-firebase.appspot.com',
    iosClientId: '394583557535-7suhp3mun1mptv9vlmiblguk2ie540qp.apps.googleusercontent.com',
    iosBundleId: 'gatosanonimos.ftkClient.RunnerTests',
  );
}
